name: Build

on:
  pull_request:
    branches: [develop]

permissions: read-all

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.x"
      - name: Run
        run: dotnet run
      - name: Output
        uses: actions/upload-artifact@v3
        with:
          name: Generated Site
          path: output/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
