name: Deploy

on:
  push:
    branches: [develop]

permissions: read-all

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: .NET
        uses: actions/setup-dotnet@v5
      - run: dotnet run -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
