name: Deploy

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"
      - run: dotnet run -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
