name: "Scan"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    - cron: "0 4 * * 5"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Analyze
        uses: github/codeql-action/analyze@v1
